---
- name: Provisionar Projeto Korp
  hosts: local
  become: true

  vars:
    project_dir: /opt/http-server-projeto-korp
    repository: https://github.com/danipeixoto87/projeto_korp.git

  tasks:

    - name: Instalar Docker e Git
      ansible.builtin.dnf:
        name:
          - docker-ce
          - git
        state: present

    - name: Garantir que o Docker esteja iniciado
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Verificar versão do Docker
      ansible.builtin.command:
        cmd: docker --version
      register: docker_version
      changed_when: false

    - name: Exibir versão do Docker
      ansible.builtin.debug:
        var: docker_version.stdout

    - name: Clonar projeto Korp
      ansible.builtin.git:
        repo: "{{ repository }}"
        dest: "{{ project_dir }}"
        version: master
        update: true

    - name: Criar rede Docker korp-network
      ansible.builtin.command:
        cmd: docker network create --driver bridge korp-network
      register: network_create
      failed_when:
        - network_create.rc != 0
        - "'already exists' not in network_create.stderr"
      changed_when: network_create.rc == 0

    - name: Subir ambiente com Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d --build
        chdir: "{{ project_dir }}"

    - name: Validar serviço Projeto Korp
      ansible.builtin.uri:
        url: http://localhost/projeto-korp
        method: GET
        status_code: 200
        return_content: true
      register: projeto_korp_response

    - name: Exibir resposta do Projeto Korp
      ansible.builtin.debug:
        msg: "{{ projeto_korp_response.content }}"
